FROM node:22-alpine AS base

# Step 1: Install dependencies
FROM base AS deps
WORKDIR /app
COPY package.json package-lock.json* ./

# Harden npm installs against transient registry/network resets in CI.
ENV NPM_CONFIG_FETCH_RETRIES=5
ENV NPM_CONFIG_FETCH_RETRY_FACTOR=2
ENV NPM_CONFIG_FETCH_RETRY_MINTIMEOUT=20000
ENV NPM_CONFIG_FETCH_RETRY_MAXTIMEOUT=120000
ENV NPM_CONFIG_FETCH_TIMEOUT=120000

RUN sh -c 'for attempt in 1 2 3; do npm ci --no-audit --no-fund && exit 0; echo "npm ci failed on attempt ${attempt}, retrying..."; sleep $((attempt * 15)); done; exit 1'

# Step 2: Build the app
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_FIREBASE_API_KEY
ENV NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY

ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN

ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID

ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET

ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID

ARG NEXT_PUBLIC_FIREBASE_APP_ID
ENV NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID

ARG NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
ENV NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=$NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID

ARG NEXT_PUBLIC_FIREBASE_DATABASE_URL
ENV NEXT_PUBLIC_FIREBASE_DATABASE_URL=$NEXT_PUBLIC_FIREBASE_DATABASE_URL

ARG NEXT_PUBLIC_MEDIAMTX_WEBRTC_BASE_URL
ENV NEXT_PUBLIC_MEDIAMTX_WEBRTC_BASE_URL=$NEXT_PUBLIC_MEDIAMTX_WEBRTC_BASE_URL

ARG NEXT_PUBLIC_MEDIAMTX_HLS_BASE_URL
ENV NEXT_PUBLIC_MEDIAMTX_HLS_BASE_URL=$NEXT_PUBLIC_MEDIAMTX_HLS_BASE_URL

ARG NEXT_PUBLIC_MEDIAMTX_PRIMARY_LABEL
ENV NEXT_PUBLIC_MEDIAMTX_PRIMARY_LABEL=$NEXT_PUBLIC_MEDIAMTX_PRIMARY_LABEL

RUN npm run build

FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production
# Next.js standalone requires this to bind to the Cloud Run network interface
ENV HOSTNAME="0.0.0.0"

ENV PORT=8080

# Copy the standalone build files
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

# Setup the entrypoint
COPY entrypoint.sh ./
RUN sed -i 's/\r$//' entrypoint.sh && chmod +x entrypoint.sh

# Start using the script
ENTRYPOINT ["./entrypoint.sh"]
