// src/lib/agents/audit-agent.ts
import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({
  apiKey: process.env.GOOGLE_GENERATIVE_AI_API_KEY || process.env.GEMINI_API_KEY || "",
});

export interface AuditResult {
  status: "confirmed" | "error" | "ambiguous";
  reasoning: string;
  actionRequired: string;
  isThreat: boolean;
}

/**
 * Aegis Vigilance Agent (Vigilance-01)
 * Audits the findings of the primary Analysis agent to eliminate false positives
 * and ensure high-integrity security decisions.
 */
export async function auditSecurityInsight(insight: {
  observation: string;
  analysis: string;
  severity: string;
}): Promise<AuditResult> {
  const prompt = `
    You are the Aegis Vigilance Agent (Vigilance-01). 
    Your task is to AUDIT the following surveillance insight generated by another AI.
    Determine if the threat is GENUINE or if it's likely a SENSOR ERROR/HALLUCINATION.

    INSIGHT TO AUDIT:
    Observation: ${insight.observation}
    Analysis: ${insight.analysis}
    Severity: ${insight.severity}

    RESPONSE FORMAT (JSON ONLY):
    {
      "status": "confirmed" | "error" | "ambiguous",
      "reasoning": "Brief explanation of why you reached this decision",
      "actionRequired": "What should the human operator do?",
      "isThreat": boolean
    }

    CRITERIA:
    - If severity is "critical" but the analysis seems far-fetched, mark as "error".
    - If there's a strong visual/logical match, mark as "confirmed".
    - If confirmed and high risk, set isThreat = true.
  `;

  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash", // Using the latest flash for rapid audit
      contents: [{ text: prompt }],
    });

    const text = response.text || "";
    if (!text) throw new Error("Empty audit response");

    const jsonMatch = text.match(/\{[\s\S]*\}/);
    if (!jsonMatch) throw new Error("Malformed audit JSON");

    return JSON.parse(jsonMatch[0]) as AuditResult;
  } catch (error) {
    console.error("[Vigilance Agent Error]:", error);
    return {
      status: "error",
      reasoning: "Neural link disruption during audit loop.",
      actionRequired: "Manual verification of video feed required.",
      isThreat: false
    };
  }
}
/**
 * Aegis Tactical Dispatcher
 * Converts a human-verified biometric match into an actionable security command.
 */
export async function dispatchVerifiedIntervention(insight: {
  observation: string;
  analysis: string;
  identifiedAs?: string;
  metadata?: any;
}): Promise<{ broadcastMessage: string; priority: string }> {
  const prompt = `
    You are the Aegis Tactical Dispatcher. 
    A human operator has just CONFIRMED a biometric match for a person of interest on surveillance.
    
    SUBJECT IDENTIFIED AS: ${insight.identifiedAs || "Unknown Subject"}
    ORIGINAL OBSERVATION: ${insight.observation}
    ANALYSIS: ${insight.analysis}

    Generate a high-priority broadcast message for security personnel to intercept/capture this person.
    The message should be professional, urgent, and include specific instructions (e.g., 'Approach with caution', 'Secure Sector B').
    
    RESPONSE FORMAT (JSON ONLY):
    {
      "broadcastMessage": "Clear, concise message for staff",
      "priority": "ALPHA" | "BRAVO" | "CHARLIE"
    }
  `;

  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: [{ text: prompt }],
    });

    const text = response.text || "";
    const jsonMatch = text.match(/\{[\s\S]*\}/);
    if (!jsonMatch) throw new Error("Malformed dispatch JSON");

    return JSON.parse(jsonMatch[0]);
  } catch (error) {
    console.error("[Dispatch Agent Error]:", error);
    return {
      broadcastMessage: `[TACTICAL_ALERT] Verified subject ${insight.identifiedAs || ""} detected. All units to primary cluster for interception.`,
      priority: "ALPHA"
    };
  }
}
